export interface ConsentItem {
  id: string;
  label: string;
  required: boolean;
  modalTitle: string;
  modalContent: string[];
}

export const userConsentItems: ConsentItem[] = [
  {
    id: 'U1',
    label: 'I have read and understood the IV Terms of Use and agree to them',
    required: true,
    modalTitle: 'Terms of Use Agreement',
    modalContent: [
      '1. Nature of Service',
      '• IV is not an investment platform',
      '• IV does not broker securities transactions',
      '• IV does not provide investment advice',
      '• IV does not solicit, recommend, endorse, or guarantee investments in any company',
      '• IV is a company introduction platform where logged-in users can view company profiles and related content',
      '',
      '2. Liability and Risks',
      '• The Terms of Use include limitations of liability applicable to IV',
      '• Direct and indirect damages arising from use of the service are subject to the limitations stated in the Terms of Use',
      '',
      '3. Prohibited Activities and Actions',
      '• Scraping, crawling, automated collection, account misuse, and security circumvention are not permitted',
      '• If violations are suspected or detected, IV may restrict access, suspend or terminate accounts, limit content access, and take legal action',
      '',
      '4. Dispute Resolution',
      '• Dispute resolution procedures and jurisdiction are governed by the Terms of Use',
    ],
  },
  {
    id: 'U2',
    label: 'I have read and understood the IV Privacy Policy and agree to it',
    required: true,
    modalTitle: 'Privacy Policy Agreement',
    modalContent: [
      '1. Account Creation Method',
      '• IV creates accounts through Google Login and processes only the minimum account information necessary for login',
      '• Example: Name, profile image, email address, Google unique identifier',
      '',
      '2. Information Not Collected',
      '• IV does not collect physical addresses or phone numbers during account creation and does not require phone number verification',
      '',
      '3. Automatically Collected Information',
      '• IV may collect minimal access logs for security and reliability purposes',
      '• Example: IP address, device information, browser type, access time, request logs, error logs',
      '• This information is used for security incident response, misuse detection, and service quality improvement',
      '',
      '4. Cookies and Analytics',
      '• IV may use essential cookies to maintain login sessions and security',
      '• IV does not use retargeting advertising cookies or ad pixels',
      '• IV may use analytics tools (e.g., GA4) for service improvement',
      '',
      '5. Third-Party Processing and Storage',
      '• IV may use third-party processors for hosting, databases, payments, and analytics',
      '• IV does not sell users\' personal information to third parties',
    ],
  },
  {
    id: 'U3',
    label: 'I understand that IV is not investment advice and I am solely responsible for all decisions and outcomes',
    required: true,
    modalTitle: 'Not Investment Advice and User Responsibility',
    modalContent: [
      '1. No Advice',
      '• IV does not provide investment, legal, tax, or accounting advice',
      '• IV does not guarantee investment outcomes, returns, losses, valuation increases, or fundraising success',
      '',
      '2. Information Limitations',
      '• Information and metrics provided in the service are for company introduction purposes and may be delayed, incomplete, or contain errors',
      '• IV does not guarantee accuracy, completeness, or timeliness',
      '',
      '3. User Responsibility',
      '• Reviewing companies, contacting them through external channels, and deciding whether to invest are entirely your responsibility',
      '• IV is not responsible for any gains or losses resulting from your decisions',
    ],
  },
  {
    id: 'U4',
    label: 'I will not collect, copy, distribute, share, publish, or republish the service\'s content, nor scrape or crawl using automated means',
    required: true,
    modalTitle: 'Content Protection and Prohibited Activities',
    modalContent: [
      '1. Permitted Use',
      '• Content viewed on the service may only be used for personal viewing purposes',
      '',
      '2. Prohibited Activities',
      '• Scraping, crawling, or automated collection, downloading, or copying',
      '• External sharing, redistribution, publishing, republishing, or leaking including screenshots',
      '• Mass storage, archiving, or dataset building of content',
      '• Circumventing access controls or disabling technical protection measures',
      '• Using content to build competing services, resell, or commercially distribute',
      '• Infringing rights, defaming others, or spreading false information',
      '',
      '3. Actions',
      '• If violations are suspected or detected, IV may restrict access, suspend or terminate accounts, limit content access, investigate through logs, and take legal action',
      '• I understand that I may be liable for all damages and liabilities arising from violations',
    ],
  },
  {
    id: 'U5',
    label: 'I understand that contacting companies through external channels is my choice and all responsibility lies between the parties, with IV bearing no liability',
    required: true,
    modalTitle: 'External Contact and Liability',
    modalContent: [
      '1. External Contact is Voluntary',
      '• You may contact companies or individuals outside the service through channels such as LinkedIn, email, website, phone, etc.',
      '',
      '2. External Activities are the Parties\' Responsibility',
      '• All conversations, proposals, promises, agreements, due diligence, investment reviews, investment decisions, transactions, fund transfers, and resulting rights or obligations conducted outside the service are entirely between the parties',
      '• IV is not responsible for success or failure, terms, legality, gains or losses, disputes, or fraud risks',
      '• You bear all risks including the risk of loss',
      '',
      '3. No Obligation to Intervene or Mediate Disputes',
      '• IV does not intervene in disputes between users or between users and companies and has no obligation to mediate or resolve disputes',
      '• Disputes must be resolved by the parties themselves, and IV is not liable for damages from disputes',
      '',
      '4. Safety Measures',
      '• If fraud reports or policy violation signals are present, IV may take safety measures such as account restrictions or content restrictions',
      '• This does not mean IV represents any party or resolves disputes',
    ],
  },
  {
    id: 'U6',
    label: 'I agree to receive IV marketing communications including feature updates, newsletters, and usage tips. This is optional and I can unsubscribe at any time',
    required: false,
    modalTitle: 'Marketing Communication Consent',
    modalContent: [
      'This is an optional consent item.',
      'You can use the service without agreeing.',
      '',
      '1. Message Types',
      '• Feature updates and release announcements',
      '• Newsletters and usage tips',
      '• Other promotional communications',
      '',
      '2. Withdrawal',
      '• You can withdraw consent at any time through the unsubscribe link in emails',
      '',
      '3. Required Administrative Notices',
      '• Security notices, service updates, payment-related notices, and terms or policy change notices may be sent regardless of this optional consent as they are necessary for service provision and protection',
    ],
  },
];

export const founderConsentItems: ConsentItem[] = [
  {
    id: 'F1',
    label: 'I have read and understood the IV Terms of Use and Privacy Policy and agree to them',
    required: true,
    modalTitle: 'Basic Terms Agreement',
    modalContent: [
      '1. Nature of Service',
      '• IV is not an investment platform',
      '• IV does not broker securities transactions',
      '• IV does not provide investment advice',
      '• IV does not solicit, recommend, endorse, or guarantee investments in any company',
      '• IV is a platform that provides company introduction information and content',
      '',
      '2. Liability and Risks',
      '• Information and metrics displayed on IV may be delayed, incomplete, or contain errors, and IV does not guarantee accuracy, completeness, or timeliness',
      '• Reviewing companies, contacting them through external channels, and deciding whether to invest are entirely your decisions and responsibility',
      '• All conversations, proposals, agreements, due diligence, investment reviews, investment decisions, transactions, fund transfers, and resulting rights or obligations conducted outside the service are entirely between the parties, and IV bears no liability',
      '',
      '3. Terms of Use and Prohibited Activities',
      '• Content that could be interpreted as investment solicitation (investment recruitment language, round funding, SAFE, valuation, term sheet, ticket size, etc.) may be restricted from the service',
      '• You agree not to collect, download, or copy content using scraping, crawling, or automation, and understand that violations may result in access restrictions, account suspension, termination, and legal action',
      '• You agree not to share, republish, redistribute, publish, or leak content including screenshots, and may be liable for violations',
      '',
      '4. Application of Terms and Policies',
      '• Service conditions, prohibited content, limitation of liability, and dispute resolution are governed by the IV Terms of Use',
      '• Personal information collection, use, storage, third-party processing, user rights, and related matters are governed by the IV Privacy Policy',
      '• IV may update terms and policies within the scope of applicable laws, and significant changes may be notified in advance',
    ],
  },
  {
    id: 'F2',
    label: 'I understand that a paid subscription is required to publish and maintain a company profile and agree to the billing, renewal, and refund policies',
    required: true,
    modalTitle: 'Subscription Billing Agreement',
    modalContent: [
      '1. Payment Processing',
      '• Subscription payments may be processed through payment providers such as Stripe',
      '• IV does not directly collect or store full card numbers, expiration dates, or CVVs',
      '• IV may retain minimal payment status information (payment success, plan type, payment date, subscription status, payment provider transaction identifier, etc.) for service operation',
      '',
      '2. Billing and Renewal',
      '• Subscriptions may automatically renew according to the billing cycle displayed at the time of payment',
      '• Fees may be charged each cycle while the subscription is active',
      '• Plan changes, upgrades, downgrades, and cancellations follow the procedures described at payment or in account settings',
      '',
      '3. Refunds and Cancellation',
      '• Refund eligibility criteria and procedures follow the payment terms and separate refund policy',
      '• Refunds may not be guaranteed',
      '• Refunds for service periods already provided or time used may be limited according to the policy',
      '',
      '4. Payment Failure and Non-Payment Actions',
      '• In case of payment failure, expired payment method, chargeback, or suspicious payment activity',
      '• IV may restrict profile visibility, limit features, suspend or terminate subscriptions without prior notice',
      '• Company profile may be made private and some features may be restricted until payment issues are resolved',
      '',
      '5. Taxes and Fees',
      '• Sales tax, VAT, or similar taxes may apply as displayed at the time of payment',
      '• Payment-related fees or exchange rate impacts may vary according to payment provider or payment method policies',
    ],
  },
  {
    id: 'F3',
    label: 'I warrant that I have secured all rights and permissions necessary to publish and disclose all submitted content including logos, images, video links, text, team information, photos, education, links, and related materials',
    required: true,
    modalTitle: 'Content Rights Warranty',
    modalContent: [
      'The Company warrants the following:',
      '',
      '• Submitted content does not infringe any third-party rights including copyright, trademark rights, privacy rights, publicity rights, or contractual restrictions',
      '',
      '• If submitted content includes personal information elements such as team member photos, bios, education, or links, the Company has obtained consent from those individuals',
      '',
      '• If rights or consent are unclear, the Company should not submit such content',
      '',
      '• If rights claims or disputes arise, the Company is liable and IV may restrict or remove content',
    ],
  },
  {
    id: 'F3A',
    label: 'I confirm that IV may display and serve founder and team photos, profile images, voice, and video content within the service, and that I have secured all necessary rights and consent',
    required: true,
    modalTitle: 'Likeness, Voice, and Video Publication Consent',
    modalContent: [
      'The Company warrants the following:',
      '',
      '1. Rights and Consent Secured',
      '• The Company has secured all rights and consent necessary to publish and display all media content submitted to IV including facial photos, profile images, voice recordings, video footage, and related text',
      '',
      '2. Scope of Consent',
      '• All individuals appearing in media have consented to such content being displayed within the IV service',
      '• Display scope may include faces, voices, statements, video excerpts, screenshots, thumbnail images, and previews',
      '',
      '3. No Third-Party Media Without Consent',
      '• The Company will not submit media containing third-party faces, voices, or videos without that individual\'s consent',
      '',
      'The Company understands and agrees to the following:',
      '',
      '1. Visibility',
      '• IV is a company introduction platform and submitted media is viewable by logged-in users',
      '',
      '2. Cannot Completely Prevent Capture',
      '• Despite policies and technical measures, IV cannot completely prevent users from capturing, storing, or sharing content',
      '',
      '3. Company Liability for Claims',
      '• The Company is liable for claims arising from media content publication including publicity rights claims, privacy claims, copyright claims, and defamation claims',
      '',
      'Minor Content Prohibition and Liability:',
      '• The Company must not submit or publish content identifying minors including facial photos, voices, videos, names, schools, or other identifying information of minors',
      '• Violation of this rule may result in IV immediately hiding or deleting content without notice and restricting accounts, suspending subscriptions, or terminating accounts',
    ],
  },
  {
    id: 'F4',
    label: 'I agree not to post content on IV that could be interpreted as investment solicitation or deal terms and accept that policy violations may result in action',
    required: true,
    modalTitle: 'Prohibited Content Policy',
    modalContent: [
      'I understand that IV is a company introduction platform, not an investment platform, and agree to the following policy:',
      '',
      '1. Purpose of Restrictions',
      '• IV does not provide investment brokerage or investment solicitation',
      '• Therefore, content should not go beyond company introduction and should not be posted in a form that could be interpreted as investment solicitation or securities offering',
      '',
      '2. Examples of Prohibited Content',
      'The Company must not post the following anywhere in the service:',
      '',
      'Investment Solicitation:',
      '• \'Please invest\', \'Currently raising\', \'Seeking investors\', \'Looking for investors\', \'Round open\', \'Funding in progress\' and similar expressions',
      '',
      'Deal Terms and Funding Information:',
      '• SAFE, valuation, term sheet, ticket size, minimum investment, target amount, timeline, deadline and similar expressions',
      '',
      'Return Expectations or Investment Inducements:',
      '• \'Guaranteed returns\', \'High returns guaranteed\', \'Safe investment\', \'Principal guaranteed\', \'No loss\', \'Expected ROI\' and similar expressions',
      '',
      'Expressions that could be interpreted as securities trading recommendations:',
      '• \'Invest now\', \'It will rise a lot\', \'Buy recommendation\', \'Sell recommendation\' and similar expressions',
      '',
      'Circumvention and Links:',
      '• Circumvention using slang, abbreviations, emojis, images, or external links to achieve the same purpose is also prohibited',
      '',
      '3. IV Action Authority',
      '• IV may automatically filter or block prohibited content',
      '• IV may request content modification, hide, or remove content, and if necessary, may take immediate action without prior notice',
      '• Repeated or serious violations may result in account restrictions, subscription suspension, termination, or making the company profile private',
      '',
      '4. Company Liability',
      '• The Company is responsible for all content submitted and posted',
      '• All complaints, third-party claims, investigations, legal disputes, and damages arising from policy violations are the Company\'s responsibility, and IV bears no liability',
    ],
  },
  {
    id: 'F5',
    label: 'I agree to connect external platform metrics to IV and consent to IV accessing, processing, storing, and displaying aggregated metrics',
    required: false,
    modalTitle: 'Metrics Integration Consent',
    modalContent: [
      '1. Purpose',
      '• IV may access aggregated data from external platforms to display more reliable company metrics and may visualize, summarize, and present this within the service',
      '',
      '2. Access Scope',
      '• Integration is intended for read-only access to aggregated metrics',
      '• IV does not request permissions to execute payments, process refunds, or change account settings',
      '• Actual access scope may vary depending on external platform APIs and permissions granted by the company',
      '',
      '3. Data Scope',
      '• IV only accesses aggregated business performance metrics',
      '• Example: Revenue, MRR, total refunds, subscription retention rate, cash balance, burn rate, traffic statistics, active users, new users, return rate, etc.',
      '• IV does not collect personal identifiers (names, emails, phone numbers, addresses, card information, etc.) of individual customers or payers',
      '',
      '4. Storage and Display',
      '• IV may store, cache, and process aggregated metrics for display and performance improvement',
      '• IV may calculate derived metrics and summary values for charts',
      '• Displayed metrics and calculation methods may change as the product evolves',
      '',
      '5. Third-Party Dependencies and No Guarantees',
      '• Metrics may be delayed, missing, inaccurate, or unavailable due to third-party service outages, API changes, permission issues, or rate limits',
      '• IV does not guarantee the accuracy, completeness, or timeliness of metrics',
      '',
      '6. Impact of Permission Removal',
      '• If the company removes permissions or permissions are invalidated, metrics or verification displays may be limited or removed',
      '• IV may discontinue or restrict integration for security or policy reasons',
    ],
  },
  {
    id: 'F6',
    label: 'I understand and agree that IV does not guarantee exposure, views, results, partner connections, or fundraising outcomes, and that liability is limited',
    required: true,
    modalTitle: 'No Exposure or Results Guarantee',
    modalContent: [
      '1. No Exposure or Results Guarantee',
      '• IV does not guarantee continuous visibility, specific placement, increased views, increased saves, increased partner connections, fundraising success, investment success, or other business outcomes',
      '• IV does not promise exposure to specific audiences or specific results',
      '',
      '2. Service Changes and Interruptions',
      '• The service is provided as-is',
      '• IV may change features, UI, display methods, search sorting logic, and exposure criteria for quality and security improvements',
      '• The service may experience interruptions or errors due to updates, maintenance, or third-party service outages',
      '',
      '3. Company Liability',
      '• The Company is responsible for the accuracy, legality, and rights clearance of submitted content and metrics',
      '• The Company must secure necessary rights and consent including portrait rights, publicity rights, and personal information',
      '• Content violating policies may result in reduced visibility, removal, or account restrictions',
      '',
      '4. No Liability for External Outcomes',
      '• Users may contact companies through external channels, and IV does not control or broker these interactions',
      '• IV is not liable for external conversations, proposals, agreements, due diligence, investment reviews, investment decisions, transactions, fund transfers, or the outcomes of rights and obligations',
      '',
      '5. Limitation of Liability',
      '• IV\'s liability for direct and indirect damages is limited as stated in the IV Terms of Use',
      '• The Company understands and agrees to these limitations',
    ],
  },
  {
    id: 'F7',
    label: 'I understand and agree that all external contacts and transactions occur entirely between the parties, IV does not broker them, and bears no liability',
    required: true,
    modalTitle: 'External Contact and Transaction Disclaimer',
    modalContent: [
      '1. IV Role Limitation',
      '• IV is a company introduction platform and does not broker investments',
      '• IV does not provide in-platform messaging',
      '• IV does not provide investor matching, introductions, negotiation support, or closing support',
      '• IV does not arrange contact between users and companies and does not participate in transactions',
      '',
      '2. External Contact is Voluntary',
      '• Users may contact companies or individuals directly through LinkedIn, email, website, or phone',
      '• External contact is voluntary between the parties, and IV does not control or guarantee it',
      '',
      '3. All External Activities are the Parties\' Responsibility',
      '• All conversations, proposals, promises, agreements, due diligence, investment reviews, investment decisions, transactions, fund transfers, and resulting rights or obligations conducted outside the service are entirely between the parties',
      '• IV is not responsible for success or failure, terms, legality, truthfulness, gains or losses, disputes, or fraud risks',
      '• All risks and losses are entirely borne by the parties',
      '',
      '4. No Obligation to Intervene or Mediate Disputes',
      '• IV does not intervene in disputes between users and companies or between users',
      '• IV has no obligation to mediate or resolve disputes',
      '• All disputes must be resolved by the parties, and IV is not liable for damages from disputes',
      '',
      '5. Actions',
      '• If fraud reports or policy violation signals are present, IV may take safety measures such as account restrictions or content restrictions',
      '• This does not mean IV represents any party or resolves disputes',
    ],
  },
  {
    id: 'F8',
    label: 'I agree to receive IV operational updates and insights emails. This is optional and can be withdrawn at any time',
    required: false,
    modalTitle: 'Operational Update Email Consent',
    modalContent: [
      'This is an optional consent item.',
      'You can register a company profile and use the service without agreeing.',
      '',
      '1. Email Types',
      'If you consent, IV may send the following emails:',
      '• Operational announcements and guidance',
      '• Feature updates and release announcements',
      '• Product tips and usage guides',
      '• Research insights or data-based content that may help company operations',
      '• Email topics and frequency may vary according to service operations',
      '',
      '2. Unsubscribe and Withdrawal',
      '• You can withdraw consent at any time by clicking the unsubscribe link at the bottom of emails',
      '• You may also change email preferences in account settings if available',
      '',
      '3. Separation from Required Notices',
      '• Required administrative notices such as security notices, payment-related notices, and terms or policy updates may be sent regardless of this optional consent',
      '• These emails are necessary for account protection and service provision',
    ],
  },
];
